Add sanity checks at the end of the keystore init

diff --git a/bin/keystore-init b/bin/keystore-init
--- a/bin/keystore-init
+++ b/bin/keystore-init
@@ -34,6 +34,18 @@ function createKeyStore() {
     exit 1
   fi
 
+  if ! keytool -list "${keytoolOpts[@]}" -alias radarbase-managementportal-ec >/dev/null 2>/dev/null; then
+    echo "FAILED TO CREATE ECDSA KEY radarbase-managementportal-ec in $keystorefile. Please try again."
+    rm "${keystorefile}"
+    exit 1
+  fi
+
+  if ! keytool -list "${keytoolOpts[@]}" -alias selfsigned >/dev/null 2>/dev/null; then
+    echo "FAILED TO CREATE ECDSA KEY selfsigned in $keystorefile. Please try again."
+    rm "${keystorefile}"
+    exit 1
+  fi
+
   chmod 400 "${keystorefile}"
 }
 
