Use stderr to print keystore-init error messages

diff --git a/bin/keystore-init b/bin/keystore-init
--- a/bin/keystore-init
+++ b/bin/keystore-init
@@ -32,18 +32,18 @@ function createKeyStore() {
   fi
 
   if [ ! -e "${keystorefile}" ]; then
-    echo "FAILED TO CREATE KEYSTORE FILE $keystorefile"
+    >&2 echo "FAILED TO CREATE KEYSTORE FILE $keystorefile"
     exit 1
   fi
 
   if ! keytool -list "${keytoolOpts[@]}" -alias radarbase-managementportal-ec >/dev/null 2>/dev/null; then
-    echo "FAILED TO CREATE ECDSA KEY radarbase-managementportal-ec in $keystorefile. Please try again."
+    >&2 echo "FAILED TO CREATE ECDSA KEY radarbase-managementportal-ec in $keystorefile. Please try again."
     rm "${keystorefile}"
     exit 1
   fi
 
   if ! keytool -list "${keytoolOpts[@]}" -alias selfsigned >/dev/null 2>/dev/null; then
-    echo "FAILED TO CREATE RSA KEY selfsigned in $keystorefile. Please try again."
+    >&2 echo "FAILED TO CREATE RSA KEY selfsigned in $keystorefile. Please try again."
     rm "${keystorefile}"
     exit 1
   fi
