Properly quote all arguments

diff --git a/bin/keystore-init b/bin/keystore-init
--- a/bin/keystore-init
+++ b/bin/keystore-init
@@ -1,36 +1,37 @@
 #!/bin/bash
 
-#cd "$( dirname "${BASH_SOURCE[0]}" )/.."
-
-set -vx
-
 cd "$(dirname "${BASH_SOURCE[0]}")/.."
 . bin/util.sh
 
 function createKeyStore() {
   keystorefile="$1"
-  KEYTOOL_OPTS="-keystore ${keystorefile} -storepass radarbase -keypass radarbase $KEYSTORE_INIT_OPTS"
+  keytoolOpts=(-keystore "${keystorefile}" -storepass radarbase -keypass radarbase $KEYSTORE_OPTS)
 
-  if ! keytool -list $KEYTOOL_OPTS -alias radarbase-managementportal-ec >/dev/null 2>/dev/null; then
-    KEYTOOL_CREATE_OPTS="-genkeypair -alias radarbase-managementportal-ec -keyalg EC -groupname secp256r1 -sigalg SHA256withECDSA -storetype PKCS12 $KEYSTORE_CREATE_OPTS"
-    if [ -n "${MANAGEMENTPORTAL_KEY_DNAME}" ]; then
-      KEYTOOL_CREATE_OPTS="$KEYTOOL_CREATE_OPTS -dname ${MANAGEMENTPORTAL_KEY_DNAME}"
-    fi
+  if ! keytool -list "${keytoolOpts[@]}" -alias radarbase-managementportal-ec >/dev/null 2>/dev/null; then
     echo "--> Generating keystore to hold EC keypair for JWT signing"
-    keytool $KEYTOOL_CREATE_OPTS $KEYTOOL_OPTS
+    createOpts=(-genkeypair -alias radarbase-managementportal-ec -keyalg EC -groupname secp256r1 -sigalg SHA256withECDSA -storetype PKCS12 $KEYSTORE_CREATE_OPTS)
+    if [ -n "${DNAME}" ]; then
+      createOpts+=(-dname "${DNAME}")
+    fi
+    keytool "${createOpts[@]}" "${keytoolOpts[@]}"
   else
     echo "--> ECDSA keypair for signing JWTs already exists. Not creating a new one."
   fi
 
-  if ! keytool -list $KEYTOOL_OPTS -alias selfsigned >/dev/null 2>/dev/null; then
-    KEYTOOL_CREATE_OPTS="-genkeypair -alias selfsigned -keyalg RSA -keysize 4096 -storetype PKCS12 $KEYSTORE_CREATE_OPTS"
-    if [ -n "${MANAGEMENTPORTAL_KEY_DNAME}" ]; then
-      KEYTOOL_CREATE_OPTS="$KEYTOOL_CREATE_OPTS -dname ${MANAGEMENTPORTAL_KEY_DNAME}"
-    fi
+  if ! keytool -list "${keytoolOpts[@]}" -alias selfsigned >/dev/null 2>/dev/null; then
     echo "--> Generating keystore to hold RSA keypair for JWT signing"
-    keytool $KEYTOOL_CREATE_OPTS $KEYTOOL_OPTS
+    createOpts=(-genkeypair -alias selfsigned -keyalg RSA -keysize 4096 -storetype PKCS12 $KEYSTORE_CREATE_OPTS)
+    if [ -n "${DNAME}" ]; then
+      createOpts+=(-dname "${DNAME}")
+    fi
+    keytool "${createOpts[@]}" "${keytoolOpts[@]}"
   else
     echo "--> RSA keypair for signing JWTs already exists. Not creating a new one."
+  fi
+
+  if [ ! -e "${keystorefile}" ]; then
+    echo "FAILED TO CREATE KEYSTORE FILE $keystorefile"
+    exit 1
   fi
 
   chmod 400 "${keystorefile}"
